# Sardinian translation for update-manager
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2010-12-17 17:42+0000\n"
"PO-Revision-Date: 2010-09-06 03:55+0000\n"
"Last-Translator: Borealis <borealis@tiscali.it>\n"
"Language-Team: Sardinian <sc@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n!=1;\n"
"X-Launchpad-Export-Date: 2011-01-04 06:47+0000\n"
"X-Generator: Launchpad (build 12138)\n"
"Language: sc\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:356 ../UpdateManager/Core/utils.py:356
msgid "0 KB"
msgstr "0 KiB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:359 ../UpdateManager/Core/utils.py:359
msgid "1 KB"
msgstr "1 KiB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:362 ../UpdateManager/Core/utils.py:362
#, python-format
msgid "%.0f KB"
msgstr "%.0f KiB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:365 ../UpdateManager/Core/utils.py:365
#, python-format
msgid "%.1f MB"
msgstr "%.1f MiB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:210 ../DistUpgrade/distro.py:425
#, python-format
msgid "Server for %s"
msgstr "Server pro %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:228 ../DistUpgrade/distro.py:234
#: ../DistUpgrade/distro.py:250
msgid "Main server"
msgstr "Server printzipale"

#: ../DistUpgrade/distro.py:254
msgid "Custom servers"
msgstr "Server personalitzados"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr ""

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Impossibile agatare files de pachetes. Forsis custu no est unu discu de "
"Ubuntu, o est pro una architetura diferente."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "Annanta de su CD no arren√®schida."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:132
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeCache.py:135
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
msgstr[1] ""

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:233
msgid "The server may be overloaded"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:343
msgid "Broken packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:344
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:637
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:647
msgid "This is most likely a transient problem, please try again later."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:650
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:656
#: ../UpdateManager/UpdateManager.py:940
msgid "Could not calculate the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:707
msgid "Error authenticating some packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:708
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:728
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:732
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:741
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:843
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:857
#, python-format
msgid "Can't install '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:858
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:867
msgid "Can't guess meta-package"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:868
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:86
msgid "Reading cache"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:189
msgid "Unable to get exclusive lock"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:190
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:236
msgid "Upgrading over remote connection not supported"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:237
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:251
msgid "Continue running under SSH?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:252
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:266
msgid "Starting additional sshd"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:267
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:275
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous its not done automatically.You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:346
#: ../DistUpgrade/DistUpgradeController.py:391
msgid "Can not upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:347
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:356
msgid "Sandbox setup failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:357
msgid "It was not possible to create the sandbox environment."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:363
msgid "Sandbox mode"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:364
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:392
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:418
msgid "Package 'debsig-verify' is installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:419
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:429
msgid "Include latest updates from the Internet?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:430
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:647
#, python-format
msgid "disabled on upgrade to %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:674
msgid "No valid mirror found"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:675
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:695
msgid "Generate default sources?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:696
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:731
msgid "Repository information invalid"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:732
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:738
msgid "Third party sources disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:739
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:779
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:782
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:830
msgid "Error during update"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:831
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:840
#: ../UpdateManager/UpdateManager.py:696
msgid "Not enough free disk space"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:841
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:869
#: ../DistUpgrade/DistUpgradeController.py:1589
msgid "Calculating the changes"
msgstr ""

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:901
msgid "Do you want to start the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:967
msgid "Upgrade canceled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:968
msgid ""
"The upgrade will cancel now and the original system state will be "
"restored.You can resume the upgrade at a later time."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:974
#: ../DistUpgrade/DistUpgradeController.py:1074
msgid "Could not download the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:975
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1026
#: ../DistUpgrade/DistUpgradeController.py:1062
#: ../DistUpgrade/DistUpgradeController.py:1167
msgid "Error during commit"
msgstr ""

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1028
#: ../DistUpgrade/DistUpgradeController.py:1064
#: ../DistUpgrade/DistUpgradeController.py:1206
msgid "Restoring original system state"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1029
#: ../DistUpgrade/DistUpgradeController.py:1043
#: ../DistUpgrade/DistUpgradeController.py:1065
msgid "Could not install the upgrades"
msgstr ""

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1034
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1039
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1075
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1155
msgid "Remove obsolete packages?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1156
#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Keep"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1156
msgid "_Remove"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1168
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1244
msgid "Required depends is not installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1245
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr ""

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1492
#: ../DistUpgrade/DistUpgradeController.py:1559
msgid "Checking package manager"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1497
msgid "Preparing the upgrade failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1498
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1514
msgid "Getting upgrade prerequisites failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1515
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1545
msgid "Updating repository information"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1577
msgid "Invalid package information"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1578
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1595
#: ../DistUpgrade/DistUpgradeController.py:1643
msgid "Fetching"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1601
#: ../DistUpgrade/DistUpgradeController.py:1647
msgid "Upgrading"
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1606
#: ../DistUpgrade/DistUpgradeController.py:1649
#: ../DistUpgrade/DistUpgradeController.py:1656
#: ../DistUpgrade/DistUpgradeController.py:1667
msgid "Upgrade complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1607
#: ../DistUpgrade/DistUpgradeController.py:1650
#: ../DistUpgrade/DistUpgradeController.py:1657
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1614
msgid "Searching for obsolete software"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1619
msgid "System upgrade is complete."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1668
msgid "The partial upgrade was completed."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:177
msgid "evms in use"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:178
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:444
#: ../DistUpgrade/DistUpgradeQuirks.py:472
#: ../DistUpgrade/DistUpgradeQuirks.py:499
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:448
#: ../DistUpgrade/DistUpgradeQuirks.py:476
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:503
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:533
msgid "No i686 CPU"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:534
msgid ""
"Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
"extension. All packages were built with optimizations requiring i686 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:570
msgid "No ARMv6 CPU"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:571
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:591
msgid "No init available"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:592
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:47
msgid "Sandbox upgrade using aufs"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:49
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:55
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:58
msgid "*DEPRECATED* this option will be ignore"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:61
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:64
msgid "Disable GNU screen support"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:66
msgid "Set datadir"
msgstr ""

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:113
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:134
#: ../DistUpgrade/DistUpgradeViewKDE.py:204
msgid "Fetching is complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:145
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:148
#: ../DistUpgrade/DistUpgradeViewGtk.py:292
#: ../DistUpgrade/DistUpgradeViewKDE.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:363
#, python-format
msgid "About %s remaining"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:151
#: ../DistUpgrade/DistUpgradeViewKDE.py:220
#, python-format
msgid "Fetching file %li of %li"
msgstr ""

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:183
#: ../DistUpgrade/DistUpgradeViewKDE.py:254
msgid "Applying changes"
msgstr ""

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:208
#: ../DistUpgrade/DistUpgradeViewKDE.py:267
msgid "dependency problems - leaving unconfigured"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:213
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid "Could not install '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:214
#: ../DistUpgrade/DistUpgradeViewKDE.py:270
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:232
#: ../DistUpgrade/DistUpgradeViewKDE.py:292
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:250
#: ../DistUpgrade/DistUpgradeViewKDE.py:315
msgid "The 'diff' command was not found"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:459
#: ../DistUpgrade/DistUpgradeViewText.py:91
msgid "A fatal error occurred"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:460
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:477
msgid "Ctrl-c pressed"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:478
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:626
msgid "To prevent data loss close all open applications and documents."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:640
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:641
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:642
#, python-format
msgid "Remove (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:643
#, python-format
msgid "No longer needed (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:644
#, python-format
msgid "Install (%s)"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:645
#, python-format
msgid "Upgrade (%s)"
msgstr ""

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:327
msgid "Show Difference >>>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:330
msgid "<<< Hide Difference"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:545
msgid "Error"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:557
msgid "&Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:559
#: ../DistUpgrade/DistUpgradeViewKDE.py:801
msgid "&Close"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:605
msgid "Show Terminal >>>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:608
msgid "<<< Hide Terminal"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:688
msgid "Information"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:739
#: ../DistUpgrade/DistUpgradeViewKDE.py:784
#: ../DistUpgrade/DistUpgradeViewKDE.py:787 ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Details"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:765
#, python-format
msgid "No longer supported %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:767
#, python-format
msgid "Remove %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:769
#: ../DistUpgrade/DistUpgradeViewText.py:178
#, python-format
msgid "Remove (was auto installed) %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:771
#, python-format
msgid "Install %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:773
#, python-format
msgid "Upgrade %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:797
#: ../DistUpgrade/DistUpgradeViewText.py:226
msgid "Restart required"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:797
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:800 ../DistUpgrade/DistUpgrade.ui.h:25
#: ../data/glade/UpdateManager.ui.h:31
msgid "_Restart Now"
msgstr ""

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:818
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:822
msgid "Cancel Upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:60
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] ""
msgstr[1] ""

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:81
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr ""

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:99
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr ""

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:148
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:152
#, python-format
msgid "This download will take about %s with your connection. "
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:254 ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Preparing to upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:255
msgid "Getting new software channels"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:256 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Getting new packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:257 ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Installing the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:258 ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Cleaning up"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:343
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
msgstr[1] ""

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:352
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:357
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:363
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:368
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:372
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:378 ../UpdateManager/UpdateManager.py:623
msgid "Your system is up-to-date"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:379
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:392
msgid "Reboot required"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:393
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid "Could not run the upgrade tool"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:211
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:211
msgid "Upgrade tool signature"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:216
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:216
msgid "Upgrade tool"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Failed to fetch"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:253
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:253
msgid "Failed to extract"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:259
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:259
msgid "Verification failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:260
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:260
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:265
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:265
msgid "Authentication failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:266
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:266
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:280
#: ../DistUpgrade/DistUpgradeFetcherCore.py:286
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:280
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:286
msgid "Can not run the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:281
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:281
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:287
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:287
#, python-format
msgid "The error message is '%s'."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:92
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:116
msgid "Aborting"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:121
msgid "Demoted:\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:154
#: ../DistUpgrade/DistUpgradeViewText.py:192
#: ../DistUpgrade/DistUpgradeViewText.py:199
msgid "Continue [yN] "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:154
#: ../DistUpgrade/DistUpgradeViewText.py:192
msgid "Details [d]"
msgstr ""

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:158
#: ../DistUpgrade/DistUpgradeViewText.py:202
msgid "y"
msgstr ""

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:161
#: ../DistUpgrade/DistUpgradeViewText.py:209
msgid "n"
msgstr ""

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:164
msgid "d"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:169
#, python-format
msgid "No longer supported: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:174
#, python-format
msgid "Remove: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:184
#, python-format
msgid "Install: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:189
#, python-format
msgid "Upgrade: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "Continue [Yn] "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:227
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:5
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "<b><big>Start the upgrade?</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "<b><big>Upgrading Ubuntu to version 11.04</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Difference between the files"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Distribution Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Restarting the computer"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Setting new software channels"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "Terminal"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Cancel Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Continue"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Replace"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Report Bug"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:26
msgid "_Resume Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "_Start Upgrade"
msgstr ""

#: ../UpdateManager/backend/InstallBackendSynaptic.py:55
msgid "Please wait, this can take some time."
msgstr ""

#: ../UpdateManager/backend/InstallBackendSynaptic.py:57
msgid "Update is complete"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:13
#: ../data/glade/UpgradePromptDialog.ui.h:4
msgid "Release Notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr ""

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr ""

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr ""

#: ../UpdateManager/GtkProgress.py:161
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""

#: ../UpdateManager/GtkProgress.py:166
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr ""

#: ../UpdateManager/UpdateManager.py:112 ../do-release-upgrade:80
msgid "Your Ubuntu release is not supported anymore."
msgstr ""

#: ../UpdateManager/UpdateManager.py:113
msgid ""
"You will not get any further security fixes or critical updates. Please "
"upgrade to a later version of Ubuntu Linux."
msgstr ""

#: ../UpdateManager/UpdateManager.py:121
msgid "Upgrade information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:376
#, python-format
msgid "Version %s: \n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:433
msgid "Downloading list of changes..."
msgstr ""

#: ../UpdateManager/UpdateManager.py:473
msgid "_Uncheck All"
msgstr ""

#: ../UpdateManager/UpdateManager.py:479
msgid "_Check All"
msgstr ""

#: ../UpdateManager/UpdateManager.py:526
#, python-format
msgid "%(count)s update has been selected."
msgid_plural "%(count)s updates have been selected."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:530
#, python-format
msgid "%s will be downloaded."
msgstr ""

#: ../UpdateManager/UpdateManager.py:541
msgid "The update has already been downloaded, but not installed"
msgid_plural "The updates have already been downloaded, but not installed"
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:545
msgid "There are no updates to install"
msgstr ""

#. TRANSLATORS: this allows to switch the order of the count of
#. updates and the download size string (if needed)
#: ../UpdateManager/UpdateManager.py:550
#, python-format
msgid "%(count_str)s %(download_str)s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:557
msgid "Unknown download size."
msgstr ""

#: ../UpdateManager/UpdateManager.py:584
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""

#: ../UpdateManager/UpdateManager.py:588
#, python-format
msgid ""
"The package information was last updated %(days_ago)s days ago.\n"
"Press the 'Check' button below to check for new software updates."
msgstr ""

#: ../UpdateManager/UpdateManager.py:593
#, python-format
msgid "The package information was last updated %(days_ago)s day ago."
msgid_plural ""
"The package information was last updated %(days_ago)s days ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:597
#, python-format
msgid "The package information was last updated %(hours_ago)s hour ago."
msgid_plural ""
"The package information was last updated %(hours_ago)s hours ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:601
msgid "The package information was last updated less than one hour ago."
msgstr ""

#: ../UpdateManager/UpdateManager.py:621 ../data/glade/UpdateManager.ui.h:23
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""

#: ../UpdateManager/UpdateManager.py:635
msgid "Software updates may be available for your computer."
msgstr ""

#: ../UpdateManager/UpdateManager.py:643
msgid "Welcome to Ubuntu"
msgstr ""

#: ../UpdateManager/UpdateManager.py:644
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:647
msgid "Software updates are available for this computer"
msgstr ""

#: ../UpdateManager/UpdateManager.py:648
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:697
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""

#: ../UpdateManager/UpdateManager.py:722
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""

#: ../UpdateManager/UpdateManager.py:774
msgid "Reading package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:789
msgid "Connecting..."
msgstr ""

#: ../UpdateManager/UpdateManager.py:799
msgid "You may not be able to check for updates or download new updates."
msgstr ""

#: ../UpdateManager/UpdateManager.py:916
msgid "Could not initialize the package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:917
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:941
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#: ../UpdateManager/UpdateManager.py:966
msgid " (New install)"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:973
#, python-format
msgid "(Size: %s)"
msgstr ""

#: ../UpdateManager/UpdateManager.py:975
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:979
#, python-format
msgid "Version %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:1010 ../do-release-upgrade:92
msgid "Release upgrade not possible right now"
msgstr ""

#: ../UpdateManager/UpdateManager.py:1011 ../do-release-upgrade:93
#, c-format, python-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""

#: ../UpdateManager/UpdateManager.py:1013 ../check-new-release-gtk:91
msgid "Downloading the release upgrade tool"
msgstr ""

#: ../UpdateManager/UpdateManager.py:1020
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr ""

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1059
msgid "Software index is broken"
msgstr ""

#: ../UpdateManager/UpdateManager.py:1060
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:128
#, python-format
msgid "Other updates (%s)"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:285
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:298
msgid "This change is not coming from a source that supports changelogs."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:304 ../UpdateManager/Core/MyCache.py:324
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:313
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:318
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:52
msgid "Failed to detect distribution"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:53
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Important security updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Recommended updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Proposed updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:67
msgid "Backports"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:68
msgid "Distribution updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:73
msgid "Other updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:82
msgid "Previous selected"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:12
msgid "It‚Äôs safer to connect the computer to AC power before updating."
msgstr ""

#: ../data/glade/UpdateManager.ui.h:14
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:21
msgid "Settings..."
msgstr ""

#: ../data/glade/UpdateManager.ui.h:22
#: ../data/glade/UpgradePromptDialog.ui.h:5
msgid "Show progress of individual files"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:24
msgid "Starting Update Manager"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:26 ../data/update-manager.desktop.in.h:3
msgid "Update Manager"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:27
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Hide this information in the future"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Install Updates"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:30
msgid "_Partial Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:32
msgid "_Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:33
msgid "updates"
msgstr ""

#: ../data/glade/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr ""

#: ../data/glade/UpgradePromptDialog.ui.h:2
msgid "Ask Me Later"
msgstr ""

#: ../data/glade/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr ""

#: ../data/glade/UpgradePromptDialog.ui.h:6
msgid "Yes, Upgrade Now"
msgstr ""

#: ../data/glade/UpgradePromptDialog.ui.h:7
msgid ""
"You can upgrade at a later time by opening Update Manager and click on "
"\"Upgrade\"."
msgstr ""

#: ../data/glade/UpgradePromptDialog.ui.h:8
msgid "You have declined to upgrade to the new Ubuntu"
msgstr ""

#: ../data/update-manager.desktop.in.h:1
msgid "Show and install available updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:2
msgid "Software Updates"
msgstr ""

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr ""

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr ""

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr ""

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr ""

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""

#: ../data/update-manager.schemas.in.h:8
msgid ""
"If this key is set, the main update list window will show the package "
"summary before the package name."
msgstr ""

#: ../data/update-manager.schemas.in.h:9
msgid "Remind to reload the channel list"
msgstr ""

#: ../data/update-manager.schemas.in.h:10
msgid "Show details of an update"
msgstr ""

#: ../data/update-manager.schemas.in.h:11
msgid "Show package summary before package name in update list"
msgstr ""

#: ../data/update-manager.schemas.in.h:12
msgid "Show version in update list"
msgstr ""

#: ../data/update-manager.schemas.in.h:13
msgid "Stores the size of the update-manager dialog"
msgstr ""

#: ../data/update-manager.schemas.in.h:14
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""

#: ../data/update-manager.schemas.in.h:15
msgid "The window size"
msgstr ""

#: ../data/update-manager.schemas.in.h:16
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../data/update-manager.schemas.in.h:17
msgid ""
"This will permanently hide the new release prompt from check-new-release-"
"gtk. Note that the small button in the main update-manager UI will still be "
"there."
msgstr ""

#: ../data/update-manager.schemas.in.h:18
msgid "make check-new-release-gtk ignore a given new release"
msgstr ""

#: ../update-manager:53 ../do-release-upgrade:33
msgid "Show version and exit"
msgstr ""

#: ../update-manager:56
msgid "Directory that contains the data files"
msgstr ""

#: ../update-manager:59
msgid "Check if a new Ubuntu release is available"
msgstr ""

#: ../update-manager:62 ../do-release-upgrade:36 ../check-new-release-gtk:142
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""

#: ../update-manager:66
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""

#: ../update-manager:73
msgid "Do not focus on map when starting"
msgstr ""

#: ../update-manager:76
msgid "Try to run a dist-upgrade"
msgstr ""

#: ../update-manager:80 ../do-release-upgrade:52
msgid "Test upgrade with a sandbox aufs overlay"
msgstr ""

#: ../update-manager:100
msgid "Running partial upgrade"
msgstr ""

#: ../do-release-upgrade:40 ../check-new-release-gtk:146
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""

#: ../do-release-upgrade:44
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""

#: ../do-release-upgrade:50
msgid "Run the specified frontend"
msgstr ""

#: ../do-release-upgrade:55
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""

#: ../do-release-upgrade:69
msgid "Checking for a new ubuntu release"
msgstr ""

#: ../do-release-upgrade:81
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""

#: ../do-release-upgrade:87
msgid "No new release found"
msgstr ""

#: ../do-release-upgrade:99
#, c-format
msgid "New release '%s' available."
msgstr ""

#: ../do-release-upgrade:100
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr ""

#: ../check-new-release-gtk:67
msgid "Ubuntu %(version)s Upgrade Available"
msgstr ""

#: ../check-new-release-gtk:107
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr ""

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr ""

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr ""

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr ""

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr ""

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr ""

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr ""

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr ""

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr ""

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr ""

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
